### ISSUE TITLE
Division problems in performScoring

### ISSUE THREAD

**Issue by pcrocker-pivotal** [mploed/ddd-strategic-design-spring-boot#2]
Certain values can lead to some BigDecimal division problems:

- Term: 12
- Amount: 500
- Income: 50000
- Rent: 650
- Cost Of Living: 200

Results in this exception:
```
2017-04-12T10:44:49.525-05:00 [APP/PROC/WEB/0] [OUT] 2017-04-12 15:44:49.525 ERROR 6 --- [nio-8080-exec-9] o.a.c.c.C.[.[.[/].[dispatcherServlet] : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.ArithmeticException: Non-terminating decimal expansion; no exact representable decimal result.] with root cause
2017-04-12T10:44:49.526-05:00 [APP/PROC/WEB/0] [OUT] at java.math.BigDecimal.divide(BigDecimal.java:1690) ~[na:1.8.0_121]
2017-04-12T10:44:49.526-05:00 [APP/PROC/WEB/0] [OUT] java.lang.ArithmeticException: Non-terminating decimal expansion; no exact representable decimal result.
2017-04-12T10:44:49.526-05:00 [APP/PROC/WEB/0] [OUT] at com.innoq.mploed.ddd.application.domain.CreditApplicationForm.getMonthlyPayment(CreditApplicationForm.java:75) ~[classes/:na]
...
```

**Comment by pcrocker-pivotal** [comment]
Amount / Term (500 / 12) = 41.666666666666667

BigDecimal doesn't like this!

**Comment by chhengchansopheaktra** [comment]
.
